import { connectProductAddOnCatalogue, connectProductServiceCatalogue } from './product-catalogue';
import type {
  CategoryDefinition,
  MockAddOn,
  MockSalon,
  ServiceImage,
} from './types';

export function deepFreeze<T>(value: T): T {
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {
    for (const nestedValue of Object.values(value as Record<string, unknown>)) {
      deepFreeze(nestedValue);
    }
    Object.freeze(value);
  }

  return value;
}

export const CANONICAL_SALON = deepFreeze<MockSalon>({
  id: 'salon-isla-nail-studio',
  name: 'Isla Nail Studio',
  slug: 'isla-nail-studio',
  tagline: 'Thoughtful nail care, shaped around you.',
  location: 'Toronto, Ontario',
});

export const CATEGORY_DEFINITIONS = deepFreeze<readonly CategoryDefinition[]>([
  { id: 'manicure', label: 'Manicure' },
  { id: 'builder_gel', label: 'Builder Gel' },
  { id: 'gel_x', label: 'Gel-X' },
  { id: 'pedicure', label: 'Pedicure' },
  { id: 'nail_art', label: 'Nail Art' },
  { id: 'combos', label: 'Combos' },
  { id: 'add_ons', label: 'Add-ons' },
]);

const ACCEPTED_ADD_ONS: readonly MockAddOn[] = [
  { id: 'addon-french', name: 'French', priceCents: 1500, durationMinutes: 15 },
  { id: 'addon-chrome', name: 'Chrome', priceCents: 1000, durationMinutes: 10 },
  { id: 'addon-simple-art', name: 'Simple Nail Art', priceCents: 1500, durationMinutes: 15 },
  { id: 'addon-detailed-art', name: 'Detailed Nail Art', priceCents: 3000, durationMinutes: 30 },
];

export const MOCK_ADD_ONS = deepFreeze(connectProductAddOnCatalogue(ACCEPTED_ADD_ONS));

const IMAGE_CATALOG = deepFreeze<Record<string, ServiceImage>>({
  bareNatural: {
    id: 'image-bare-natural',
    src: '/assets/images/services/manicure-bare-natural.webp',
    alt: 'Natural nails with a clean, glossy finish',
  },
  builderOverlay: {
    id: 'image-builder-overlay',
    src: '/assets/images/services/manicure-builder-overlay.webp',
    alt: 'Structured builder gel overlay on almond-shaped nails',
  },
  cateye: {
    id: 'image-cateye',
    src: '/assets/images/services/manicure-cateye.webp',
    alt: 'Deep cat-eye nail art with a reflective finish',
  },
  comboFrench: {
    id: 'image-combo-french',
    src: '/assets/images/services/combo-french-luster.webp',
    alt: 'Coordinated French manicure and pedicure',
  },
  comboPinkBuilder: {
    id: 'image-combo-pink-builder',
    src: '/assets/images/services/combo-pink-builder-luster.webp',
    alt: 'Pink builder gel manicure with a polished pedicure',
  },
  comboTaupe: {
    id: 'image-combo-taupe',
    src: '/assets/images/services/combo-taupe-luster.webp',
    alt: 'Taupe gel manicure and pedicure combination',
  },
  hardGel: {
    id: 'image-hard-gel',
    src: '/assets/images/services/extensions-hard-gel-burgundy.webp',
    alt: 'Sculpted burgundy hard-gel extensions',
  },
  manicureFrench: {
    id: 'image-manicure-french',
    src: '/assets/images/services/manicure-french.webp',
    alt: 'Crisp French manicure on softly shaped nails',
  },
  gelNude: {
    id: 'image-gel-nude',
    src: '/assets/images/services/manicure-gel-nude.webp',
    alt: 'Glossy nude gel manicure',
  },
  lusterPearl: {
    id: 'image-luster-pearl',
    src: '/assets/images/services/manicure-luster-pearl.webp',
    alt: 'Pearlescent manicure with a luminous finish',
  },
  pearlChrome: {
    id: 'image-pearl-chrome',
    src: '/assets/images/services/manicure-pearl-chrome.webp',
    alt: 'Pearl chrome manicure catching the light',
  },
  russianClean: {
    id: 'image-russian-clean',
    src: '/assets/images/services/manicure-russian-clean.webp',
    alt: 'Precision manicure with clean cuticle work',
  },
  pedicureBare: {
    id: 'image-pedicure-bare',
    src: '/assets/images/services/pedicure-bare-natural.webp',
    alt: 'Natural pedicure with a clean glossy finish',
  },
  pedicureFrench: {
    id: 'image-pedicure-french',
    src: '/assets/images/services/pedicure-french.webp',
    alt: 'Fresh French pedicure',
  },
  pedicureRedClassic: {
    id: 'image-pedicure-red-classic',
    src: '/assets/images/services/pedicure-red-classic.webp',
    alt: 'Classic red pedicure',
  },
  pedicureRedLuster: {
    id: 'image-pedicure-red-luster',
    src: '/assets/images/services/pedicure-red-luster.webp',
    alt: 'Glossy red spa pedicure',
  },
});

const ART_ADD_ON_IDS = ACCEPTED_ADD_ONS.map(addOn => addOn.id);
const LIGHT_ART_ADD_ON_IDS = ['addon-french', 'addon-chrome', 'addon-simple-art'];

export const CANONICAL_SERVICES = deepFreeze(connectProductServiceCatalogue([
  {
    id: 'svc-manicure-russian',
    name: 'Russian Manicure',
    category: 'manicure',
    shortDescription: 'Precision dry cuticle care with meticulous shaping and polish.',
    longDescription: 'A detailed dry-manicure technique that refines the cuticle area before careful shaping and your chosen gel finish.',
    price: { behavior: 'starts_at', amountCents: 6500 },
    durationMinutes: 90,
    image: IMAGE_CATALOG.russianClean!,
    featured: true,
    badge: 'Signature',
    compatibleAddOnIds: ART_ADD_ON_IDS,
  },
  {
    id: 'svc-manicure-gel',
    name: 'Gel Manicure',
    category: 'manicure',
    shortDescription: 'Long-wear gel colour with cuticle care and shaping.',
    longDescription: 'Nail shaping, gentle cuticle care and a glossy gel colour selected from the studio colour collection.',
    price: { behavior: 'fixed', amountCents: 5000 },
    durationMinutes: 60,
    image: IMAGE_CATALOG.gelNude!,
    featured: true,
    badge: 'Most booked',
    compatibleAddOnIds: ART_ADD_ON_IDS,
  },
  {
    id: 'svc-manicure-classic',
    name: 'Classic Manicure',
    category: 'manicure',
    shortDescription: 'Essential nail and cuticle care finished with regular polish.',
    longDescription: 'A tidy, restorative manicure with shaping, cuticle care, light hydration and your choice of regular polish.',
    price: { behavior: 'fixed', amountCents: 3500 },
    durationMinutes: 45,
    image: IMAGE_CATALOG.bareNatural!,
    featured: false,
    compatibleAddOnIds: LIGHT_ART_ADD_ON_IDS,
  },
  {
    id: 'svc-builder-overlay',
    name: 'BIAB / Builder Gel Overlay',
    category: 'builder_gel',
    shortDescription: 'Strengthen natural nails with a structured builder-gel overlay.',
    longDescription: 'A structured overlay is balanced over the natural nail to add strength while maintaining a refined, wearable profile.',
    price: { behavior: 'starts_at', amountCents: 5500 },
    durationMinutes: 90,
    image: IMAGE_CATALOG.builderOverlay!,
    featured: true,
    badge: 'Best seller',
    compatibleAddOnIds: ART_ADD_ON_IDS,
  },
  {
    id: 'svc-builder-gel-colour',
    name: 'BIAB + Gel Colour',
    category: 'builder_gel',
    shortDescription: 'Builder-gel strength finished with a full gel colour.',
    longDescription: 'A strengthening BIAB base is shaped and refined, then finished with a gel colour for durable, polished wear.',
    price: { behavior: 'starts_at', amountCents: 6500 },
    durationMinutes: 105,
    image: IMAGE_CATALOG.lusterPearl!,
    featured: false,
    badge: 'Long-wear',
    compatibleAddOnIds: ART_ADD_ON_IDS,
  },
  {
    id: 'svc-builder-refill',
    name: 'BIAB Refill / Builder Gel Fill',
    category: 'builder_gel',
    shortDescription: 'Rebalance and refresh an existing builder-gel overlay.',
    longDescription: 'Existing product is refined and rebalanced at the growth area before reshaping and the chosen finish are applied.',
    price: { behavior: 'starts_at', amountCents: 5000 },
    durationMinutes: 90,
    image: IMAGE_CATALOG.comboTaupe!,
    featured: false,
    compatibleAddOnIds: ART_ADD_ON_IDS,
  },
  {
    id: 'svc-builder-full-set',
    name: 'Builder Gel Full Set',
    category: 'builder_gel',
    shortDescription: 'A sculpted full set with structure tailored to your desired length.',
    longDescription: 'A complete structured-gel set built for strength, balance and a slim profile. Final pricing reflects the chosen length and shape.',
    price: { behavior: 'range', minCents: 7000, maxCents: 8500 },
    durationMinutes: 120,
    image: IMAGE_CATALOG.hardGel!,
    featured: false,
    badge: 'Sculpted',
    compatibleAddOnIds: ART_ADD_ON_IDS,
  },
  {
    id: 'svc-gelx-full-set',
    name: 'Gel-X Full Set',
    category: 'gel_x',
    shortDescription: 'Soft-gel extensions customized to your preferred shape and length.',
    longDescription: 'Lightweight soft-gel tips are fitted, shaped and finished to create a consistent extension set without acrylic.',
    price: { behavior: 'starts_at', amountCents: 7500 },
    durationMinutes: 105,
    image: IMAGE_CATALOG.hardGel!,
    featured: true,
    badge: 'Extensions',
    compatibleAddOnIds: ART_ADD_ON_IDS,
  },
  {
    id: 'svc-gelx-refill',
    name: 'Gel-X Refill',
    category: 'gel_x',
    shortDescription: 'Refresh compatible Gel-X extensions with renewed shape and finish.',
    longDescription: 'We assess the existing set, rebalance compatible growth and restore the shape before applying the selected finish.',
    price: { behavior: 'starts_at', amountCents: 6500 },
    durationMinutes: 90,
    image: IMAGE_CATALOG.cateye!,
    featured: false,
    compatibleAddOnIds: ART_ADD_ON_IDS,
  },
  {
    id: 'svc-gelx-removal',
    name: 'Gel-X Removal',
    category: 'gel_x',
    shortDescription: 'Careful removal of an existing soft-gel extension set.',
    longDescription: 'Extensions are gently reduced and soaked away, followed by light natural-nail shaping and conditioning.',
    price: { behavior: 'fixed', amountCents: 2000 },
    durationMinutes: 30,
    image: IMAGE_CATALOG.bareNatural!,
    featured: false,
    compatibleAddOnIds: [],
  },
  {
    id: 'svc-pedicure-classic',
    name: 'Classic Pedicure',
    category: 'pedicure',
    shortDescription: 'Essential foot and nail care with a regular-polish finish.',
    longDescription: 'Includes a soak, nail shaping, cuticle care, smoothing and hydration before your chosen regular polish.',
    price: { behavior: 'fixed', amountCents: 4500 },
    durationMinutes: 60,
    image: IMAGE_CATALOG.pedicureRedClassic!,
    featured: false,
    compatibleAddOnIds: LIGHT_ART_ADD_ON_IDS,
  },
  {
    id: 'svc-pedicure-gel',
    name: 'Gel Pedicure',
    category: 'pedicure',
    shortDescription: 'Detailed pedicure care finished with long-wear gel colour.',
    longDescription: 'A complete pedicure with shaping, cuticle care, smoothing and hydration, finished with glossy gel colour.',
    price: { behavior: 'starts_at', amountCents: 5500 },
    durationMinutes: 75,
    image: IMAGE_CATALOG.pedicureFrench!,
    featured: false,
    compatibleAddOnIds: LIGHT_ART_ADD_ON_IDS,
  },
  {
    id: 'svc-pedicure-spa',
    name: 'Spa Pedicure',
    category: 'pedicure',
    shortDescription: 'Extended exfoliation, massage and restorative foot care.',
    longDescription: 'A slow, restorative ritual with soak, detailed grooming, exfoliation, massage, hydration and a polished finish.',
    price: { behavior: 'fixed', amountCents: 7000 },
    durationMinutes: 90,
    image: IMAGE_CATALOG.pedicureRedLuster!,
    featured: true,
    badge: 'Ritual',
    compatibleAddOnIds: LIGHT_ART_ADD_ON_IDS,
  },
  {
    id: 'svc-art-tier-one',
    name: 'Tier One Art',
    category: 'nail_art',
    shortDescription: 'One solid colour, chrome or simple French.',
    longDescription: 'A polished full-service set with one colour and a restrained finish such as chrome or simple French detailing.',
    price: { behavior: 'fixed', amountCents: 9500 },
    durationMinutes: 90,
    image: IMAGE_CATALOG.manicureFrench!,
    featured: false,
    compatibleAddOnIds: [],
  },
  {
    id: 'svc-art-tier-two',
    name: 'Tier Two Art',
    category: 'nail_art',
    shortDescription: 'French, ombré, aura or detailed art.',
    longDescription: 'A full-service set with considered art across multiple nails, including French, ombré, aura or comparable detailing.',
    price: { behavior: 'fixed', amountCents: 11000 },
    durationMinutes: 120,
    image: IMAGE_CATALOG.pearlChrome!,
    featured: false,
    compatibleAddOnIds: [],
  },
  {
    id: 'svc-art-tier-three',
    name: 'Tier Three Art',
    category: 'nail_art',
    shortDescription: 'Advanced layered art with multiple colours and textures.',
    longDescription: 'A full-service statement set combining layered techniques, several colours and dimensional or textured details.',
    price: { behavior: 'fixed', amountCents: 12500 },
    durationMinutes: 150,
    image: IMAGE_CATALOG.cateye!,
    featured: false,
    compatibleAddOnIds: [],
  },
  {
    id: 'svc-art-tier-four',
    name: 'Tier Four Art',
    category: 'nail_art',
    shortDescription: 'A fully custom, high-detail set designed collaboratively.',
    longDescription: 'Our most involved art appointment, reserved for intricate custom concepts, extensive layering and experimental finishes.',
    price: { behavior: 'varies' },
    durationMinutes: 240,
    image: IMAGE_CATALOG.lusterPearl!,
    featured: false,
    badge: 'Bespoke',
    compatibleAddOnIds: [],
  },
  {
    id: 'svc-combo-gel',
    name: 'Gel Manicure + Gel Pedicure',
    category: 'combos',
    shortDescription: 'A coordinated gel manicure and pedicure in one visit.',
    longDescription: 'Complete gel care for hands and feet, including shaping, cuticle work and coordinated long-wear colour.',
    price: { behavior: 'fixed', amountCents: 9500 },
    durationMinutes: 120,
    image: IMAGE_CATALOG.comboFrench!,
    featured: true,
    badge: 'Save $10',
    compatibleAddOnIds: LIGHT_ART_ADD_ON_IDS,
  },
  {
    id: 'svc-combo-biab',
    name: 'BIAB + Gel Pedicure',
    category: 'combos',
    shortDescription: 'Builder-gel strength for hands with a polished gel pedicure.',
    longDescription: 'A structured BIAB manicure and complete gel pedicure planned together for a consistent, durable finish.',
    price: { behavior: 'starts_at', amountCents: 11500 },
    durationMinutes: 150,
    image: IMAGE_CATALOG.comboPinkBuilder!,
    featured: false,
    compatibleAddOnIds: LIGHT_ART_ADD_ON_IDS,
  },
  {
    id: 'svc-addon-french',
    name: 'French',
    category: 'add_ons',
    shortDescription: 'A crisp French finish tailored to your chosen shape.',
    longDescription: 'Add a classic, micro or softly curved French tip to a compatible colour service.',
    price: { behavior: 'fixed', amountCents: 1500 },
    durationMinutes: 15,
    image: IMAGE_CATALOG.manicureFrench!,
    featured: false,
    compatibleAddOnIds: [],
  },
  {
    id: 'svc-addon-chrome',
    name: 'Chrome',
    category: 'add_ons',
    shortDescription: null,
    longDescription: null,
    price: { behavior: 'fixed', amountCents: 1000 },
    durationMinutes: 10,
    image: IMAGE_CATALOG.pearlChrome!,
    featured: false,
    compatibleAddOnIds: [],
  },
  {
    id: 'svc-addon-simple-art',
    name: 'Simple Nail Art',
    category: 'add_ons',
    shortDescription: 'Minimal accents, dots, lines or a restrained design.',
    longDescription: 'A small amount of hand-painted detail or simple accents added to a compatible manicure service.',
    price: { behavior: 'starts_at', amountCents: 1500 },
    durationMinutes: 15,
    image: IMAGE_CATALOG.cateye!,
    featured: false,
    compatibleAddOnIds: [],
  },
  {
    id: 'svc-addon-detailed-art',
    name: 'Detailed Nail Art',
    category: 'add_ons',
    shortDescription: 'Layered, hand-painted or dimensional art quoted by complexity.',
    longDescription: 'Reserve extra studio time for detailed custom art. Final pricing reflects the number of nails and techniques selected.',
    price: { behavior: 'varies' },
    durationMinutes: 30,
    image: IMAGE_CATALOG.lusterPearl!,
    featured: false,
    compatibleAddOnIds: [],
  },
  {
    id: 'svc-addon-consultation',
    name: 'Complimentary Nail Consultation',
    category: 'add_ons',
    shortDescription: 'Plan shape, length, colour and art before a complex appointment.',
    longDescription: 'A complimentary studio conversation for clients planning a transformation, repair or detailed custom set.',
    price: { behavior: 'free' },
    durationMinutes: 30,
    image: IMAGE_CATALOG.bareNatural!,
    featured: false,
    badge: 'Complimentary',
    compatibleAddOnIds: [],
  },
]));

export const CANONICAL_SERVICE_IDS = deepFreeze(
  CANONICAL_SERVICES.map(service => service.id),
);
