import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const Env = createEnv({
  server: {
    CLERK_SECRET_KEY: z.string().min(1),
    DATABASE_URL: z.string().optional(),
    LOGTAIL_SOURCE_TOKEN: z.string().optional(),
    STRIPE_SECRET_KEY: z.string().min(1),
    STRIPE_WEBHOOK_SECRET: z.string().min(1),
    BILLING_PLAN_ENV: z.enum(['dev', 'test', 'prod']),
    // Twilio (for SMS OTP and notifications)
    TWILIO_ACCOUNT_SID: z.string().optional(),
    TWILIO_AUTH_TOKEN: z.string().optional(),
    TWILIO_VERIFY_SERVICE_SID: z.string().optional(),
    TWILIO_PHONE_NUMBER: z.string().optional(), // For sending SMS notifications
    RESEND_API_KEY: z.string().optional(),
    RESEND_FROM_EMAIL: z.string().optional(),
    RESEND_REPLY_TO_EMAIL: z.string().optional(),
    // Cloudinary (for photo uploads)
    CLOUDINARY_CLOUD_NAME: z.string().optional(),
    CLOUDINARY_API_KEY: z.string().optional(),
    CLOUDINARY_API_SECRET: z.string().optional(),
    SENTRY_ORG: z.string().optional(),
    SENTRY_PROJECT: z.string().optional(),
    SENTRY_AUTH_TOKEN: z.string().optional(),
    SENTRY_RELEASE: z.string().optional(),
    SENTRY_ENVIRONMENT: z.string().optional(),
    GOOGLE_CALENDAR_ENABLED: z.string().optional(),
    GOOGLE_CALENDAR_ID: z.string().optional(),
    GOOGLE_CALENDAR_CLIENT_EMAIL: z.string().optional(),
    GOOGLE_CALENDAR_PRIVATE_KEY: z.string().optional(),
    GOOGLE_OAUTH_CLIENT_ID: z.string().optional(),
    GOOGLE_OAUTH_CLIENT_SECRET: z.string().optional(),
    GOOGLE_OAUTH_REDIRECT_URI: z.string().url().optional(),
    INTEGRATION_ENCRYPTION_KEY: z.string().optional(),
    INTEGRATION_ENCRYPTION_KEY_VERSION: z.coerce.number().int().positive().optional(),
    OAUTH_STATE_SECRET: z.string().optional(),
    TWILIO_CONNECT_APP_SID: z.string().optional(),
    TWILIO_CONNECT_REDIRECT_URI: z.string().url().optional(),
    LUSTER_ROOT_DOMAIN: z.string().optional(),
    TENANT_SUBDOMAINS_ENABLED: z.enum(['true', 'false']).optional(),
    TENANT_SUBDOMAIN_ALLOWLIST: z.string().optional(),
    CLERK_AUTHORIZED_PARTIES: z.string().optional(),
    APP_ENV: z.enum(['development', 'staging', 'production']).optional(),
    REDIS_URL: z.string().optional(),
    SUPER_ADMIN_AUTH_MODE: z.enum(['password', 'twilio']).optional(),
    SUPER_ADMIN_TEST_LOGIN_ENABLED: z.enum(['true', 'false']).optional(),
    SUPER_ADMIN_TEST_TOOLS_ENABLED: z.enum(['true', 'false']).optional(),
    SUPER_ADMIN_TEST_PHONE: z.string().optional(),
    SUPER_ADMIN_TEST_PASSWORD: z.string().optional(),
    ALLOW_STAGING_SUPER_ADMIN_PASSWORD: z.enum(['true', 'false']).optional(),
    LEGACY_OTP_AUTH_ENABLED: z.enum(['true', 'false']).optional(),
    LEGACY_OTP_TEST_FIXTURE_ENABLED: z.enum(['true', 'false']).optional(),
    VERCEL_GIT_COMMIT_SHA: z.string().optional(),
    GITHUB_SHA: z.string().optional(),
    VERCEL_ENV: z.string().optional(),
    // Dev mode: real admin_user.id for FK-safe dev super admin
    DEV_SUPER_ADMIN_ID: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().optional(),
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().min(1),
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: z.string().min(1),
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.string().min(1),
    NEXT_PUBLIC_SENTRY_DSN: z.string().optional(),
    // DEV ONLY: Enable dev role switcher
    NEXT_PUBLIC_DEV_MODE: z.enum(['true', 'false']).optional(),
  },
  shared: {
    NODE_ENV: z.enum(['test', 'development', 'production']).optional(),
  },
  // You need to destructure all the keys manually
  runtimeEnv: {
    CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
    DATABASE_URL: process.env.DATABASE_URL,
    LOGTAIL_SOURCE_TOKEN: process.env.LOGTAIL_SOURCE_TOKEN,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    BILLING_PLAN_ENV: process.env.BILLING_PLAN_ENV,
    TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
    TWILIO_VERIFY_SERVICE_SID: process.env.TWILIO_VERIFY_SERVICE_SID,
    TWILIO_PHONE_NUMBER: process.env.TWILIO_PHONE_NUMBER,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL,
    RESEND_REPLY_TO_EMAIL: process.env.RESEND_REPLY_TO_EMAIL,
    CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
    SENTRY_ORG: process.env.SENTRY_ORG,
    SENTRY_PROJECT: process.env.SENTRY_PROJECT,
    SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
    SENTRY_RELEASE: process.env.SENTRY_RELEASE,
    SENTRY_ENVIRONMENT: process.env.SENTRY_ENVIRONMENT,
    GOOGLE_CALENDAR_ENABLED: process.env.GOOGLE_CALENDAR_ENABLED,
    GOOGLE_CALENDAR_ID: process.env.GOOGLE_CALENDAR_ID,
    GOOGLE_CALENDAR_CLIENT_EMAIL: process.env.GOOGLE_CALENDAR_CLIENT_EMAIL,
    GOOGLE_CALENDAR_PRIVATE_KEY: process.env.GOOGLE_CALENDAR_PRIVATE_KEY,
    GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
    GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
    GOOGLE_OAUTH_REDIRECT_URI: process.env.GOOGLE_OAUTH_REDIRECT_URI,
    INTEGRATION_ENCRYPTION_KEY: process.env.INTEGRATION_ENCRYPTION_KEY,
    INTEGRATION_ENCRYPTION_KEY_VERSION: process.env.INTEGRATION_ENCRYPTION_KEY_VERSION,
    OAUTH_STATE_SECRET: process.env.OAUTH_STATE_SECRET,
    TWILIO_CONNECT_APP_SID: process.env.TWILIO_CONNECT_APP_SID,
    TWILIO_CONNECT_REDIRECT_URI: process.env.TWILIO_CONNECT_REDIRECT_URI,
    LUSTER_ROOT_DOMAIN: process.env.LUSTER_ROOT_DOMAIN,
    TENANT_SUBDOMAINS_ENABLED: process.env.TENANT_SUBDOMAINS_ENABLED,
    TENANT_SUBDOMAIN_ALLOWLIST: process.env.TENANT_SUBDOMAIN_ALLOWLIST,
    CLERK_AUTHORIZED_PARTIES: process.env.CLERK_AUTHORIZED_PARTIES,
    APP_ENV: process.env.APP_ENV,
    REDIS_URL: process.env.REDIS_URL,
    SUPER_ADMIN_AUTH_MODE: process.env.SUPER_ADMIN_AUTH_MODE,
    SUPER_ADMIN_TEST_LOGIN_ENABLED: process.env.SUPER_ADMIN_TEST_LOGIN_ENABLED,
    SUPER_ADMIN_TEST_TOOLS_ENABLED: process.env.SUPER_ADMIN_TEST_TOOLS_ENABLED,
    SUPER_ADMIN_TEST_PHONE: process.env.SUPER_ADMIN_TEST_PHONE,
    SUPER_ADMIN_TEST_PASSWORD: process.env.SUPER_ADMIN_TEST_PASSWORD,
    ALLOW_STAGING_SUPER_ADMIN_PASSWORD: process.env.ALLOW_STAGING_SUPER_ADMIN_PASSWORD,
    LEGACY_OTP_AUTH_ENABLED: process.env.LEGACY_OTP_AUTH_ENABLED,
    LEGACY_OTP_TEST_FIXTURE_ENABLED: process.env.LEGACY_OTP_TEST_FIXTURE_ENABLED,
    VERCEL_GIT_COMMIT_SHA: process.env.VERCEL_GIT_COMMIT_SHA,
    GITHUB_SHA: process.env.GITHUB_SHA,
    VERCEL_ENV: process.env.VERCEL_ENV,
    DEV_SUPER_ADMIN_ID: process.env.DEV_SUPER_ADMIN_ID,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
      process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL,
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
      process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
    NEXT_PUBLIC_DEV_MODE: process.env.NEXT_PUBLIC_DEV_MODE,
    NODE_ENV: process.env.NODE_ENV,
  },
});
