export const ownerMenuAssistantCopy = {
  en: {
    launcher: 'Menu assistant',
    open: 'Open Menu assistant',
    close: 'Close Menu assistant',
    title: 'Menu assistant',
    description: 'Move services in your menu. It cannot change prices or booking settings.',
    prompt: 'What should move?',
    placeholder: 'Move Gel manicure before Pedicure',
    prepare: 'Prepare menu preview',
    supported: 'Supported: “Move [service] before/after [service]”. Use quotes around a name if helpful.',
    review: 'Review menu order',
    unchanged: 'Only service order will change. Prices, durations, categories, and bookings stay the same.',
    menuScope: 'This updates the base Services menu. Booking-page groups and featured services may still use their own placement.',
    chooseExact: 'Choose the exact services',
    selectService: 'Select service',
    move: 'Move',
    before: 'Before',
    after: 'After',
    preview: 'Preview order',
    applying: 'Applying…',
    apply: 'Apply menu order',
    restored: 'Menu order restored.',
    unavailable: 'Undo is unavailable.',
    updated: 'Menu order updated.',
    restoring: 'Restoring…',
    undo: 'Undo this change',
    wait: 'Please wait for this menu request to finish.',
    chooseDifferent: 'Choose two different services from this salon menu.',
    noPreview: 'The menu assistant did not return a preview.',
    noOp: 'That service is already in that position. Nothing changed.',
    invalid: 'Try “Move Gel manicure before Pedicure.” This assistant only changes menu order.',
    chooseNames: 'Choose the services you mean. The assistant will not guess a name.',
    noConfirmation: 'The menu change was not confirmed. Check your menu and try again.',
    noUndoConfirmation: 'The undo was not confirmed. Refresh the menu before trying again.',
    undoUnavailable: 'Undo is no longer safe because the menu changed after this action.',
    checkStatus: 'Check request status',
    current: 'Current',
    afterApplying: 'After applying',
    stale: 'This preview is no longer current. Refresh the menu and prepare a new preview.',
    unsafeUndo: 'Undo is no longer safe. Refresh the menu to see the current order.',
    refresh: 'Refresh menu',
    refreshed: 'Menu refreshed. Prepare a new preview before applying.',
    refreshFailed: 'The menu could not be refreshed.',
  },
  fr: {
    launcher: 'Assistant du menu',
    open: 'Ouvrir l’assistant du menu',
    close: 'Fermer l’assistant du menu',
    title: 'Assistant du menu',
    description: 'Réorganisez les services du menu. Les prix et réglages de réservation ne peuvent pas être modifiés.',
    prompt: 'Quel service faut-il déplacer?',
    placeholder: 'Move Manucure gel before Pédicure',
    prepare: 'Préparer l’aperçu du menu',
    supported: 'Pris en charge : « Move [service] before/after [service] ». Utilisez des guillemets autour d’un nom au besoin.',
    review: 'Vérifier l’ordre du menu',
    unchanged: 'Seul l’ordre des services changera. Les prix, durées, catégories et réservations restent inchangés.',
    menuScope: 'Cela met à jour le menu Services de base. Les groupes et services en vedette de la page de réservation peuvent garder leur propre placement.',
    chooseExact: 'Choisissez les services exacts',
    selectService: 'Sélectionner un service',
    move: 'Déplacer',
    before: 'Avant',
    after: 'Après',
    preview: 'Aperçu de l’ordre',
    applying: 'Application…',
    apply: 'Appliquer l’ordre du menu',
    restored: 'Ordre du menu rétabli.',
    unavailable: 'Annulation indisponible.',
    updated: 'Ordre du menu mis à jour.',
    restoring: 'Restauration…',
    undo: 'Annuler cette modification',
    wait: 'Veuillez attendre la fin de cette demande.',
    chooseDifferent: 'Choisissez deux services différents de ce menu.',
    noPreview: 'L’assistant n’a pas retourné d’aperçu.',
    noOp: 'Ce service est déjà à cette position. Aucun changement.',
    invalid: 'Essayez « Move Manucure gel before Pédicure ». Cet assistant ne modifie que l’ordre du menu.',
    chooseNames: 'Choisissez les services concernés. L’assistant ne devinera pas un nom.',
    noConfirmation: 'La modification du menu n’a pas été confirmée. Vérifiez le menu et réessayez.',
    noUndoConfirmation: 'L’annulation n’a pas été confirmée. Actualisez le menu avant de réessayer.',
    undoUnavailable: 'L’annulation n’est plus sûre, car le menu a changé après cette action.',
    checkStatus: 'Vérifier l’état de la demande',
    current: 'Actuellement',
    afterApplying: 'Après application',
    stale: 'Cet aperçu n’est plus à jour. Actualisez le menu et préparez un nouvel aperçu.',
    unsafeUndo: 'L’annulation n’est plus sûre. Actualisez le menu pour voir l’ordre actuel.',
    refresh: 'Actualiser le menu',
    refreshed: 'Menu actualisé. Préparez un nouvel aperçu avant d’appliquer.',
    refreshFailed: 'Le menu n’a pas pu être actualisé.',
  },
} as const;

export type OwnerMenuAssistantLocale = keyof typeof ownerMenuAssistantCopy;
