/**
 * Headed responsive checks for the premium account gate across the required
 * viewport matrix. Seeds the accepted draft + account phase via localStorage
 * (generated by seed-gen.ts with the real storage modules), so the gate
 * renders exactly as it does after "Save my site".
 */
import { readFileSync } from 'node:fs';

import { expect, test } from '@playwright/test';

const BASE = process.env.LIVE_BASE_URL ?? 'http://127.0.0.1:4191';
const EVIDENCE = process.env.LIVE_EVIDENCE_DIR
  ?? '/tmp/luster-premium-account-gate/evidence/responsive';
const SEED: Record<string, string> = JSON.parse(
  readFileSync('/tmp/luster-premium-account-gate/gate-seed.json', 'utf8'),
);

const VIEWPORTS = [
  { height: 568, name: '320x568', width: 320 },
  { height: 667, name: '375x667', width: 375 },
  { height: 844, name: '390x844', width: 390 },
  { height: 932, name: '430x932', width: 430 },
  { height: 1024, name: '768x1024', width: 768 },
  { height: 800, name: '1180x800', width: 1180 },
  { height: 900, name: '1440x900', width: 1440 },
];

const seedGate = async (page: import('@playwright/test').Page) => {
  await page.goto(`${BASE}/onboarding-v1`);
  await page.evaluate((entries) => {
    window.localStorage.clear();
    window.sessionStorage.clear();
    for (const [key, value] of Object.entries(entries)) {
      window.localStorage.setItem(key, value);
    }
  }, SEED);
  await page.goto(`${BASE}/onboarding-v1?account=1`);
  await expect(page.getByRole('heading', {
    level: 1,
    name: /Save your site\.\s*Keep building anywhere\./,
  })).toBeVisible({ timeout: 30_000 });
};

const expectNoHorizontalOverflow = async (page: import('@playwright/test').Page) => {
  const overflow = await page.evaluate(() => ({
    inner: window.innerWidth,
    scroll: document.documentElement.scrollWidth,
  }));
  expect(overflow.scroll, `scrollWidth ${overflow.scroll} > viewport ${overflow.inner}`)
    .toBeLessThanOrEqual(overflow.inner + 1);
};

for (const viewport of VIEWPORTS) {
  test(`gate at ${viewport.name}`, async ({ page }) => {
    test.setTimeout(120_000);
    await page.setViewportSize({ height: viewport.height, width: viewport.width });
    await seedGate(page);

    // Every choice reachable
    const email = page.getByRole('button', { name: 'Continue with email' });
    await email.scrollIntoViewIfNeeded();
    await expect(email).toBeVisible();
    const login = page.getByRole('button', { name: 'Log in' });
    await login.scrollIntoViewIfNeeded();
    await expect(login).toBeVisible();
    const returnLink = page.getByRole('button', { name: 'Return to Review' });
    await returnLink.scrollIntoViewIfNeeded();
    await expect(returnLink).toBeVisible();
    await expectNoHorizontalOverflow(page);
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ fullPage: true, path: `${EVIDENCE}/gate-${viewport.name}.png` });

    // Email entry
    await email.click();
    await expect(page.getByLabel('Email address')).toBeVisible();
    await expectNoHorizontalOverflow(page);
    await page.screenshot({ fullPage: true, path: `${EVIDENCE}/email-${viewport.name}.png` });
  });
}

test('gate error state and reduced motion at 390x844', async ({ browser }) => {
  test.setTimeout(180_000);
  const context = await browser.newContext({
    reducedMotion: 'reduce',
    viewport: { height: 844, width: 390 },
  });
  const page = await context.newPage();
  await seedGate(page);
  await page.screenshot({ fullPage: true, path: `${EVIDENCE}/reduced-motion-390x844.png` });

  // Error state: submit while offline → mapped owner-facing error
  await page.getByRole('button', { name: 'Continue with email' }).click();
  await page.getByLabel('Email address').fill('owner@example.com');
  await context.setOffline(true);
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page.getByRole('alert')).toBeVisible({ timeout: 20_000 });
  await page.screenshot({ path: `${EVIDENCE}/error-390x844.png` });
  await context.setOffline(false);
  await context.close();
});
